import React, { useState, useEffect } from 'react';
import { CheckCheck, Plus, ArrowLeft, Trash2, CheckCircle2, Share2 } from 'lucide-react';
import confetti from 'canvas-confetti';
import { api } from '../services/api';
import GroceryItemCard from '../components/GroceryItemCard';
import ProgressBar from '../components/ProgressBar';
import EditItemModal from '../components/EditItemModal';
import { LoadingState, ErrorState, EmptyState } from '../components/StateViews';

export default function ShoppingListPage({ listId, onBack, onNavigate }) {
  const [list, setList] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [filter, setFilter] = useState('all'); // 'all', 'pending', 'purchased'
  const [editingItem, setEditingItem] = useState(null);
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const fetchList = async () => {
    try {
      setLoading(true);
      const data = await api.getListById(listId);
      setList(data);
      setError(null);
    } catch (err) {
      console.error('Failed to load grocery list:', err);
      setError('Could not load the requested grocery list.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (listId) {
      fetchList();
    }
  }, [listId]);

  const handleTogglePurchase = async (itemId, isPurchased) => {
    // Optimistic UI update
    setList((prev) => {
      if (!prev) return prev;
      const updatedItems = prev.items.map((item) =>
        item.id === itemId ? { ...item, isPurchased, purchasedAt: isPurchased ? new Date() : null } : item
      );
      const activeItems = updatedItems.filter((i) => i.status === 'active');
      const purchasedCount = activeItems.filter((i) => i.isPurchased).length;
      return {
        ...prev,
        items: updatedItems,
        stats: {
          ...prev.stats,
          purchased: purchasedCount,
          pending: activeItems.length - purchasedCount,
          percentComplete: activeItems.length > 0 ? Math.round((purchasedCount / activeItems.length) * 100) : 0,
        },
      };
    });

    try {
      await api.togglePurchase(itemId, isPurchased);
      // Trigger confetti if all active items completed
      if (isPurchased && list) {
        const remaining = list.items.filter((i) => i.status === 'active' && !i.isPurchased && i.id !== itemId).length;
        if (remaining === 0) {
          confetti({
            particleCount: 80,
            spread: 60,
            origin: { y: 0.7 },
          });
        }
      }
    } catch (err) {
      console.error('Failed to toggle purchase:', err);
      fetchList(); // Revert on error
    }
  };

  const handleMarkAllComplete = async () => {
    try {
      const updated = await api.markAllPurchased(listId);
      setList(updated);
      confetti({
        particleCount: 120,
        spread: 80,
        origin: { y: 0.6 },
      });
    } catch (err) {
      console.error('Failed to mark all complete:', err);
    }
  };

  const handleSaveItemEdit = async (updatedItem) => {
    try {
      await api.updateItem(updatedItem.id, updatedItem);
      fetchList();
    } catch (err) {
      console.error('Failed to update item:', err);
    }
  };

  const handleDeleteItem = async (itemId) => {
    try {
      await api.deleteItem(itemId);
      setList((prev) => {
        if (!prev) return prev;
        return {
          ...prev,
          items: prev.items.filter((i) => i.id !== itemId),
        };
      });
    } catch (err) {
      console.error('Failed to delete item:', err);
    }
  };

  const handleAddNewItem = () => {
    const newItem = {
      name: '',
      quantity: 1,
      unit: 'packet',
      category: 'General',
      notes: null,
      status: 'active',
      groceryListId: listId,
    };
    setEditingItem(newItem);
    setIsEditModalOpen(true);
  };

  const handleSaveNewItem = async (item) => {
    try {
      if (item.id) {
        await api.updateItem(item.id, item);
      } else {
        await api.addItemToList(listId, item);
      }
      fetchList();
    } catch (err) {
      console.error('Failed to save item:', err);
    }
  };

  const handleShareList = () => {
    if (!list) return;
    const textLines = [
      `🛒 ${list.title}`,
      `Generated by MessyList AI\n`,
      ...list.items
        .filter((i) => i.status === 'active')
        .map((i) => `${i.isPurchased ? '☑' : '☐'} ${i.name} — ${i.quantity} ${i.unit}${i.notes ? ` (${i.notes})` : ''}`),
    ];
    navigator.clipboard.writeText(textLines.join('\n'));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) return <LoadingState message="Loading your shopping checklist..." />;
  if (error || !list) return <ErrorState message={error} onRetry={fetchList} />;

  const activeItems = list.items.filter((i) => i.status === 'active');
  const cancelledItems = list.items.filter((i) => i.status === 'cancelled');

  const filteredActiveItems = activeItems.filter((item) => {
    if (filter === 'pending') return !item.isPurchased;
    if (filter === 'purchased') return item.isPurchased;
    return true;
  });

  const allCompleted = activeItems.length > 0 && activeItems.every((i) => i.isPurchased);

  return (
    <div className="fade-in" style={{ maxWidth: 840, margin: '0 auto' }}>
      {/* Top Navigation */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1.25rem' }}>
        <button onClick={onBack} className="btn btn-ghost btn-sm" id="back-to-lists-btn">
          <ArrowLeft size={16} />
          <span>Back to All Lists</span>
        </button>

        <div style={{ display: 'flex', gap: '0.5rem' }}>
          <button
            onClick={handleShareList}
            className="btn btn-secondary btn-sm"
            title="Copy plain text grocery list for WhatsApp"
            id="share-list-btn"
          >
            <Share2 size={14} />
            <span>{copied ? 'Copied!' : 'Share / Copy'}</span>
          </button>

          <button
            onClick={handleAddNewItem}
            className="btn btn-primary btn-sm"
            id="add-item-checklist-btn"
          >
            <Plus size={14} />
            <span>Add Item</span>
          </button>
        </div>
      </div>

      {/* Checklist Header */}
      <div className="card" style={{ marginBottom: '1.5rem', padding: '1.5rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem' }}>
          <div>
            <span style={{ fontSize: '0.75rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', color: 'var(--accent-primary)' }}>
              TODAY'S SHOPPING CHECKLIST
            </span>
            <h1 style={{ fontSize: '1.85rem', marginTop: '0.2rem' }}>{list.title}</h1>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', marginTop: '0.25rem' }}>
              Created on {new Date(list.createdAt).toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' })}
            </p>
          </div>

          {!allCompleted && activeItems.length > 0 && (
            <button
              onClick={handleMarkAllComplete}
              className="btn btn-secondary btn-sm"
              id="mark-all-complete-btn"
            >
              <CheckCheck size={16} color="var(--accent-primary)" />
              <span>Mark All Complete</span>
            </button>
          )}
        </div>

        {/* Progress Bar */}
        <ProgressBar
          completed={list.stats?.purchased || 0}
          total={list.stats?.active || activeItems.length}
        />

        {/* Filter Tabs */}
        <div style={{ display: 'flex', gap: '0.5rem', marginTop: '1rem', borderTop: '1px solid var(--border-subtle)', paddingTop: '1rem' }}>
          <button
            onClick={() => setFilter('all')}
            className={`btn btn-sm ${filter === 'all' ? 'btn-primary' : 'btn-secondary'}`}
          >
            All Items ({activeItems.length})
          </button>
          <button
            onClick={() => setFilter('pending')}
            className={`btn btn-sm ${filter === 'pending' ? 'btn-primary' : 'btn-secondary'}`}
          >
            Pending ({list.stats?.pending || 0})
          </button>
          <button
            onClick={() => setFilter('purchased')}
            className={`btn btn-sm ${filter === 'purchased' ? 'btn-primary' : 'btn-secondary'}`}
          >
            Purchased ({list.stats?.purchased || 0})
          </button>
        </div>
      </div>

      {/* Success Celebration Banner if 100% */}
      {allCompleted && (
        <div
          className="card fade-in"
          style={{
            background: 'var(--accent-light)',
            borderColor: 'var(--accent-primary)',
            color: 'var(--accent-text)',
            marginBottom: '1.5rem',
            display: 'flex',
            alignItems: 'center',
            gap: '0.75rem',
            padding: '1rem 1.25rem',
          }}
        >
          <CheckCircle2 size={24} color="var(--accent-primary)" />
          <div>
            <div style={{ fontWeight: 700, fontSize: '0.95rem' }}>All items bought! Restock complete 🎉</div>
            <div style={{ fontSize: '0.85rem' }}>
              Your roommate will be thrilled. The purchase history has been archived.
            </div>
          </div>
        </div>
      )}

      {/* Active Grocery Items */}
      {filteredActiveItems.length === 0 ? (
        <EmptyState
          icon="🛒"
          title={filter === 'pending' ? 'All active items are bought!' : 'No items match filter'}
          description={filter === 'pending' ? 'Great job! You finished every grocery item in this list.' : 'Try selecting All Items to see your full shopping list.'}
        />
      ) : (
        <div className="items-list">
          {filteredActiveItems.map((item) => (
            <GroceryItemCard
              key={item.id}
              item={item}
              isReviewMode={false}
              onTogglePurchase={handleTogglePurchase}
              onEdit={(it) => {
                setEditingItem(it);
                setIsEditModalOpen(true);
              }}
              onDelete={handleDeleteItem}
            />
          ))}
        </div>
      )}

      {/* Cancelled / Delegated Section */}
      {cancelledItems.length > 0 && (
        <div style={{ marginTop: '2.5rem' }}>
          <h3 style={{ fontSize: '1.1rem', color: 'var(--text-secondary)', marginBottom: '0.75rem' }}>
            Cancelled / Delegated Items ({cancelledItems.length})
          </h3>
          <p style={{ fontSize: '0.825rem', color: 'var(--text-tertiary)', marginBottom: '0.75rem' }}>
            Excluded from this shopping run because another roommate is already bringing them.
          </p>

          <div className="items-list">
            {cancelledItems.map((item) => (
              <GroceryItemCard
                key={item.id}
                item={item}
                isReviewMode={false}
                onDelete={handleDeleteItem}
              />
            ))}
          </div>
        </div>
      )}

      {/* Edit Modal */}
      <EditItemModal
        isOpen={isEditModalOpen}
        item={editingItem}
        onClose={() => setIsEditModalOpen(false)}
        onSave={handleSaveNewItem}
      />
    </div>
  );
}
